import { Schema } from "effect";

import {
  type DocumentedFreePool,
  documentedFreePoolSchema,
  type ProviderManifest,
  providerManifestSchema,
} from "./providerContract.js";

export const freePoolSnapshotSource =
  "https://github.com/diegosouzapw/OmniRoute/blob/release/v3.8.50/docs/reference/FREE_TIERS.md";
export const acknowledgementVersion = "omniroute-3.8.50-2026-06-17";
const decodeDocumentedFreePool = Schema.decodeUnknownSync(documentedFreePoolSchema);
const decodeProviderManifest = Schema.decodeUnknownSync(providerManifestSchema);

export const freePoolSnapshot: ReadonlyArray<DocumentedFreePool> = [
  ["agy", "agy", "claude-opus-4-6-thinking", "keyless", 0, "avoid"],
  ["api-airforce", "api-airforce", "x-ai/grok-3", "recurring-daily", 24_000_000, "caution"],
  ["arcee-free", "arcee-ai", "arcee-ai/trinity-large-preview:free", "recurring-daily", 4_800_000, "caution"],
  ["bazaarlink", "bazaarlink", "auto:free", "recurring-daily", 3_600_000, "caution"],
  ["blackbox", "blackbox", "gpt-4o", "keyless", 0, "avoid"],
  ["bluesminds", "bluesminds", "gpt-4o", "recurring-daily", 7_200_000, "ambiguous"],
  ["cerebras", "cerebras", "zai-glm-4.7", "recurring-daily", 30_000_000, "caution"],
  ["cloudflare-ai", "cloudflare-ai", "@cf/meta/llama-3.3-70b-instruct", "recurring-daily", 30_000_000, "caution"],
  ["cohere", "cohere", "command-a-reasoning-08-2025", "recurring-monthly", 800_000, "caution"],
  ["coze", "coze", "claude-3-7-sonnet-20250514", "recurring-daily", 0, "avoid"],
  ["duckduckgo-web", "duckduckgo-web", "gpt-5.4-mini", "keyless", 0, "avoid"],
  ["felo-web", "felo-web", "felo-chat", "keyless", 0, "avoid"],
  ["friendliai", "friendliai", "meta-llama-3.1-70b-instruct", "keyless", 0, "avoid"],
  ["gemini-free", "gemini", "gemini-2.5-flash", "recurring-daily", 60_000_000, "caution"],
  ["github-models", "github-models", "cohere/cohere-command-a", "recurring-daily", 18_000_000, "caution"],
  ["groq", "groq", "meta-llama/llama-4-scout-17b-16e-instruct", "recurring-daily", 15_000_000, "caution"],
  ["hackclub", "hackclub", "meta-llama/llama-3.3-70b-instruct", "keyless", 0, "caution"],
  ["huggingchat", "huggingchat", "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT", "recurring-monthly", 500_000, "caution"],
  ["huggingface", "huggingface", "meta-llama/llama-3.1-8b-instruct", "recurring-monthly", 200_000, "caution"],
  ["iflytek", "iflytek", "generalv3.5", "keyless", 0, "avoid"],
  ["inference-net", "inference-net", "meta-llama/Llama-3.3-70B-Instruct", "recurring-monthly", 0, "caution"],
  ["kiro", "kiro", "claude-sonnet-4.5", "recurring-monthly", 25_000, "avoid"],
  ["liquid", "liquid", "liquid-lfm-40b", "keyless", 0, "unknown"],
  ["llm7-free", "llm7", "gpt-4o-mini-2024-07-18", "recurring-daily", 150_000_000, "caution"],
  ["mistral", "mistral", "mistral-large-latest", "recurring-monthly", 1_000_000_000, "caution"],
  ["morph", "morph", "morph-v3-large", "recurring-monthly", 400_000, "ok"],
  ["muse-spark-web", "muse-spark-web", "muse-spark", "keyless", 0, "avoid"],
  ["nlpcloud", "nlpcloud", "llama-3-8b-instruct", "recurring-monthly", 0, "avoid"],
  ["ollama-cloud", "ollama-cloud", "deepseek-v4-pro", "recurring-monthly", 20_000_000, "ambiguous"],
  ["opencode", "opencode", "big-pickle", "keyless", 0, "avoid"],
  ["openrouter-free", "openrouter", "auto", "recurring-daily", 1_200_000, "caution"],
  ["pollinations", "pollinations", "openai", "keyless", 0, "caution"],
  ["puter", "puter", "gpt-5.5", "keyless", 0, "caution"],
  ["qwen-web", "qwen-web", "qwen3.8-max-preview", "keyless", 0, "avoid"],
  ["reka", "reka", "reka-flash-3", "recurring-monthly", 0, "caution"],
  ["sambanova", "sambanova", "MiniMax-M2.7", "recurring-daily", 6_000_000, "caution"],
  ["sparkdesk", "sparkdesk", "lite", "keyless", 0, "caution"],
  ["t3-web", "t3-web", "claude-opus-4", "recurring-daily", 0, "avoid"],
  ["uncloseai", "uncloseai", "adamo1139/Hermes-3-Llama-3.1-8B-FP8-Dynamic", "keyless", 0, "caution"],
  ["ovhcloud-anon", "ovhcloud", "gpt-oss-120b", "keyless", 0, "ok"],
  ["navy-free", "navy", "shared-pool", "recurring-daily", 4_500_000, "ok"],
  ["aihorde-anon", "aihorde", "aphrodite/TheDrummer/Cydonia-24B-v4.3", "keyless", 0, "ok"],
  ["nara-free", "nara", "tencent-hy3", "recurring-daily", 150_000_000, "caution"],
].map(([poolId, providerId, modelId, freeType, estimatedMonthlyTokens, termsStatus]) =>
  decodeDocumentedFreePool({ poolId, providerId, modelId, freeType, estimatedMonthlyTokens, termsStatus }),
);

export const documentedFreePoolCount = freePoolSnapshot.length;

export const documentedRecurringTokenEstimate = freePoolSnapshot.reduce(
  (estimatedTokens, freePool) => estimatedTokens + freePool.estimatedMonthlyTokens,
  0,
);

const activeProviderCatalog: ReadonlyArray<ProviderManifest> = [
  [
    "api-airforce",
    "API Airforce",
    "https://api.airforce/v1/chat/completions",
    "api-airforce",
    "caution",
    "api-airforce",
    "daily",
    800_000,
    "x-ai/grok-3",
    ["text", "reasoning", "tools"],
    "https://api.airforce/docs",
  ],
  [
    "bazaarlink",
    "BazaarLink",
    "https://bazaarlink.ai/api/v1/chat/completions",
    "bazaarlink",
    "caution",
    "bazaarlink",
    "daily",
    120_000,
    "auto:free",
    ["text", "reasoning", "tools"],
    "https://bazaarlink.ai/docs",
  ],
  [
    "blackbox",
    "Blackbox API",
    "https://api.blackbox.ai/v1/chat/completions",
    "blackbox",
    "avoid",
    "blackbox",
    "unquantified",
    0,
    "gpt-4o",
    ["text", "tools"],
    "https://docs.blackbox.ai/api-reference/introduction",
  ],
  [
    "bluesminds",
    "Bluesminds",
    "https://api.bluesminds.com/v1/chat/completions",
    "bluesminds",
    "ambiguous",
    "bluesminds",
    "daily",
    240_000,
    "gpt-4o",
    ["text", "tools"],
    "https://bluesminds.com",
  ],
  [
    "cerebras",
    "Cerebras",
    "https://api.cerebras.ai/v1/chat/completions",
    "cerebras",
    "caution",
    "cerebras",
    "daily",
    1_000_000,
    "zai-glm-4.7",
    ["text", "tools"],
    "https://inference-docs.cerebras.ai/support/rate-limits",
  ],
  [
    "cloudflare-ai",
    "Cloudflare Workers AI",
    "https://api.cloudflare.com/client/v4/accounts/account-id/ai/v1/chat/completions",
    "cloudflare-ai",
    "caution",
    "cloudflare-ai",
    "daily",
    1_000_000,
    "@cf/meta/llama-3.3-70b-instruct",
    ["text", "tools"],
    "https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/",
  ],
  [
    "cohere",
    "Cohere",
    "https://api.cohere.com/compatibility/v1/chat/completions",
    "cohere",
    "caution",
    "cohere",
    "monthly",
    800_000,
    "command-a-reasoning-08-2025",
    ["text", "reasoning", "tools"],
    "https://docs.cohere.com/docs/compatibility-api",
  ],
  [
    "friendliai",
    "FriendliAI",
    "https://api.friendli.ai/serverless/v1/chat/completions",
    "friendliai",
    "avoid",
    "friendliai",
    "unquantified",
    0,
    "meta-llama-3.1-70b-instruct",
    ["text", "tools"],
    "https://friendli.ai/docs/guides/serverless_endpoints/openai_compatibility",
  ],
  [
    "gemini",
    "Google Gemini",
    "https://generativelanguage.googleapis.com/v1beta",
    "google-ai-studio",
    "caution",
    "gemini-free",
    "daily",
    2_000_000,
    "gemini-2.5-flash",
    ["text", "reasoning", "tools"],
    "https://ai.google.dev/gemini-api/docs/rate-limits",
  ],
  [
    "groq",
    "Groq",
    "https://api.groq.com/openai/v1/chat/completions",
    "groq",
    "caution",
    "groq",
    "daily",
    500_000,
    "meta-llama/llama-4-scout-17b-16e-instruct",
    ["text", "tools"],
    "https://console.groq.com/docs/rate-limits",
  ],
  [
    "hackclub",
    "Hack Club AI",
    "https://ai.hackclub.com/proxy/v1/chat/completions",
    "hackclub",
    "caution",
    "hackclub",
    "unquantified",
    0,
    "meta-llama/llama-3.3-70b-instruct",
    ["text"],
    "https://ai.hackclub.com",
  ],
  [
    "huggingface",
    "Hugging Face Inference",
    "https://router.huggingface.co/v1/chat/completions",
    "huggingface",
    "caution",
    "huggingface",
    "monthly",
    200_000,
    "meta-llama/llama-3.1-8b-instruct",
    ["text", "tools"],
    "https://huggingface.co/docs/inference-providers/guides/openai",
  ],
  [
    "iflytek",
    "iFlytek Spark",
    "https://spark-api-open.xf-yun.com/v1/chat/completions",
    "iflytek",
    "avoid",
    "iflytek",
    "unquantified",
    0,
    "generalv3.5",
    ["text"],
    "https://www.xfyun.cn/doc/spark/Web.html",
  ],
  [
    "inference-net",
    "Inference.net",
    "https://api.inference.net/v1/chat/completions",
    "inference-net",
    "caution",
    "inference-net",
    "unquantified",
    0,
    "meta-llama/Llama-3.3-70B-Instruct",
    ["text", "tools"],
    "https://docs.inference.net/features/openai-sdk",
  ],
  [
    "liquid",
    "Liquid AI",
    "https://inference.liquid.ai/v1/chat/completions",
    "liquid",
    "unknown",
    "liquid",
    "unquantified",
    0,
    "liquid-lfm-40b",
    ["text"],
    "https://docs.liquid.ai/api-reference/inference-api",
  ],
  [
    "llm7",
    "LLM7",
    "https://api.llm7.io/v1/chat/completions",
    "llm7",
    "caution",
    "llm7-free",
    "daily",
    5_000_000,
    "gpt-4o-mini-2024-07-18",
    ["text", "tools"],
    "https://llm7.io",
  ],
  [
    "mistral",
    "Mistral AI",
    "https://api.mistral.ai/v1/chat/completions",
    "mistral",
    "caution",
    "mistral",
    "monthly",
    1_000_000_000,
    "mistral-large-latest",
    ["text", "reasoning", "tools"],
    "https://docs.mistral.ai/deployment/laplateforme/tier/",
  ],
  [
    "morph",
    "Morph",
    "https://api.morphllm.com/v1/chat/completions",
    "morph",
    "ok",
    "morph",
    "monthly",
    400_000,
    "morph-v3-large",
    ["text", "tools"],
    "https://docs.morphllm.com/api-reference/introduction",
  ],
  [
    "ollama-cloud",
    "Ollama Cloud",
    "https://ollama.com/v1/chat/completions",
    "ollama-cloud",
    "ambiguous",
    "ollama-cloud",
    "monthly",
    20_000_000,
    "deepseek-v4-pro",
    ["text", "reasoning", "tools"],
    "https://docs.ollama.com/api/openai-compatibility",
  ],
  [
    "openrouter",
    "OpenRouter free models",
    "https://openrouter.ai/api/v1/chat/completions",
    "openrouter-oauth",
    "caution",
    "openrouter-free",
    "daily",
    40_000,
    "openrouter/free",
    ["text", "reasoning", "tools"],
    "https://openrouter.ai/docs/guides/overview/auth/oauth",
  ],
  [
    "pollinations",
    "Pollinations",
    "https://gen.pollinations.ai/v1/chat/completions",
    "pollinations",
    "caution",
    "pollinations",
    "unquantified",
    0,
    "openai",
    ["text"],
    "https://github.com/pollinations/pollinations/blob/master/APIDOCS.md",
  ],
  [
    "puter",
    "Puter",
    "https://api.puter.com/puterai/openai/v1/chat/completions",
    "puter",
    "caution",
    "puter",
    "unquantified",
    0,
    "gpt-5.5",
    ["text", "reasoning", "tools"],
    "https://docs.puter.com/AI/chat/",
  ],
  [
    "reka",
    "Reka",
    "https://api.reka.ai/v1/chat/completions",
    "reka",
    "caution",
    "reka",
    "unquantified",
    0,
    "reka-flash-3",
    ["text", "reasoning", "tools"],
    "https://docs.reka.ai/api-reference/chat",
  ],
  [
    "sambanova",
    "SambaNova",
    "https://api.sambanova.ai/v1/chat/completions",
    "sambanova",
    "caution",
    "sambanova",
    "daily",
    200_000,
    "MiniMax-M2.7",
    ["text", "reasoning", "tools"],
    "https://docs.sambanova.ai/cloud/docs/get-started/overview",
  ],
  [
    "sparkdesk",
    "SparkDesk",
    "https://spark-api-open.xf-yun.com/v1/chat/completions",
    "sparkdesk",
    "caution",
    "sparkdesk",
    "unquantified",
    0,
    "lite",
    ["text"],
    "https://www.xfyun.cn/doc/spark/Web.html",
  ],
  [
    "uncloseai",
    "UncloseAI",
    "https://hermes.ai.unturf.com/v1/chat/completions",
    undefined,
    "caution",
    "uncloseai",
    "unquantified",
    0,
    "adamo1139/Hermes-3-Llama-3.1-8B-FP8-Dynamic",
    ["text"],
    "https://hermes.ai.unturf.com",
  ],
  [
    "ovhcloud",
    "OVHcloud AI Endpoints",
    "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1/chat/completions",
    undefined,
    "ok",
    "ovhcloud-anon",
    "unquantified",
    0,
    "gpt-oss-120b",
    ["text", "reasoning", "tools"],
    "https://help.ovhcloud.com/csm/en-public-cloud-ai-endpoints-getting-started?id=kb_article_view&sysparm_article=KB0065400",
  ],
  [
    "navy",
    "NavyAI",
    "https://api.navy/v1/chat/completions",
    "navy",
    "ok",
    "navy-free",
    "daily",
    150_000,
    "llama-3.3-70b-instruct",
    ["text", "tools"],
    "https://api.navy",
  ],
  [
    "aihorde",
    "AI Horde",
    "https://oai.aihorde.net/v1/chat/completions",
    undefined,
    "ok",
    "aihorde-anon",
    "unquantified",
    0,
    "aphrodite/TheDrummer/Cydonia-24B-v4.3",
    ["text"],
    "https://aihorde.net/api",
  ],
  [
    "nara",
    "NaraRouter",
    "https://router.bynara.id/v1/chat/completions",
    "nara",
    "caution",
    "nara-free",
    "daily",
    5_000_000,
    "tencent-hy3",
    ["text"],
    "https://bynara.id",
  ],
].map(
  ([
    providerId,
    displayName,
    endpoint,
    credentialId,
    termsStatus,
    poolId,
    reset,
    estimatedTokens,
    modelId,
    capabilities,
    source,
  ]) =>
    decodeProviderManifest({
      providerId,
      displayName,
      protocolFamily: providerId === "gemini" ? "google-generative" : "openai-chat",
      endpoint,
      authentication: credentialId === undefined ? "keyless" : "api-key",
      credentialId,
      termsStatus,
      acknowledgementVersion,
      activation: "active",
      freeTierWindow: { poolId, reset, estimatedTokens },
      models: [{ modelId, capabilities }],
      source,
    }),
);

const unavailableProviderCatalog: ReadonlyArray<ProviderManifest> = [
  [
    "coze",
    "Coze",
    "https://api.coze.com/v3/chat",
    "avoid",
    "coze",
    "claude-3-7-sonnet-20250514",
    "unsupported-protocol",
    "https://www.coze.com/open/docs/developer_guides/coze_api_overview",
  ],
  [
    "nlpcloud",
    "NLP Cloud",
    "https://api.nlpcloud.io/v1/gpu/llama-3-8b-instruct/chatbot",
    "avoid",
    "nlpcloud",
    "llama-3-8b-instruct",
    "unsupported-protocol",
    "https://docs.nlpcloud.com/#chatbot-and-conversational-ai",
  ],
  [
    "github-models",
    "GitHub Models",
    "https://models.github.ai/inference/chat/completions",
    "caution",
    "github-models",
    "cohere/cohere-command-a",
    "retired-contract",
    "https://docs.github.com/en/github-models/prototyping-with-ai-models",
  ],
  [
    "agy",
    "AGY",
    "https://cloudcode-pa.googleapis.com",
    "avoid",
    "agy",
    "claude-opus-4-6-thinking",
    "synthetic-identity",
    "https://github.com/diegosouzapw/OmniRoute",
  ],
  [
    "arcee-ai",
    "Arcee free relay",
    "https://api.kilo.ai/api/gateway/chat/completions",
    "caution",
    "arcee-free",
    "arcee-ai/trinity-large-preview:free",
    "unverified-contract",
    "https://github.com/diegosouzapw/OmniRoute",
  ],
  [
    "duckduckgo-web",
    "DuckDuckGo web chat",
    "https://duckduckgo.com/duckchat/v1/chat",
    "avoid",
    "duckduckgo-web",
    "gpt-5.4-mini",
    "browser-cookie",
    "https://duckduckgo.com/duckai",
  ],
  [
    "felo-web",
    "Felo web search",
    "https://felo.ai/api-proxy/main/search/threads",
    "avoid",
    "felo-web",
    "felo-chat",
    "browser-cookie",
    "https://felo.ai",
  ],
  [
    "huggingchat",
    "HuggingChat",
    "https://huggingface.co/chat/conversation",
    "caution",
    "huggingchat",
    "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT",
    "browser-cookie",
    "https://huggingface.co/chat",
  ],
  [
    "kiro",
    "Kiro",
    "https://codewhisperer.us-east-1.amazonaws.com/generateAssistantResponse",
    "avoid",
    "kiro",
    "claude-sonnet-4.5",
    "synthetic-identity",
    "https://kiro.dev",
  ],
  [
    "muse-spark-web",
    "Meta AI web",
    "https://www.meta.ai/api/graphql",
    "avoid",
    "muse-spark-web",
    "muse-spark",
    "browser-cookie",
    "https://www.meta.ai",
  ],
  [
    "opencode",
    "OpenCode synthetic identity",
    "https://opencode.ai/zen/v1/chat/completions",
    "avoid",
    "opencode",
    "big-pickle",
    "synthetic-identity",
    "https://opencode.ai/docs/zen/",
  ],
  [
    "qwen-web",
    "Qwen web chat",
    "https://chat.qwen.ai/api/chat/completions",
    "avoid",
    "qwen-web",
    "qwen3.8-max-preview",
    "browser-cookie",
    "https://chat.qwen.ai",
  ],
  [
    "t3-web",
    "T3 Chat web",
    "https://t3.chat/api/chat",
    "avoid",
    "t3-web",
    "claude-opus-4",
    "browser-cookie",
    "https://t3.chat",
  ],
].map(([providerId, displayName, endpoint, termsStatus, poolId, modelId, unavailableReason, source]) =>
  decodeProviderManifest({
    providerId,
    displayName,
    protocolFamily: "openai-chat",
    endpoint,
    authentication: "keyless",
    termsStatus,
    acknowledgementVersion,
    activation: "unavailable",
    unavailableReason,
    freeTierWindow: { poolId, reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId, capabilities: ["text"] }],
    source,
  }),
);

export const freeProviderCatalog: ReadonlyArray<ProviderManifest> = [
  ...activeProviderCatalog,
  ...unavailableProviderCatalog,
];

export const activeFreeProviderCount = activeProviderCatalog.length;
export const unavailableFreeProviderCount = unavailableProviderCatalog.length;
