import { Schema } from "effect";

import {
  type DocumentedFreePool,
  documentedFreePoolSchema,
  type ProviderManifest,
  providerManifestSchema,
} from "./providerContract.js";

export const acknowledgementVersion = "omniroute-3.8.50-2026-06-17";
const decodeDocumentedFreePool = Schema.decodeUnknownSync(documentedFreePoolSchema);
const decodeProviderManifest = Schema.decodeUnknownSync(providerManifestSchema);

export const freePoolSnapshot: ReadonlyArray<DocumentedFreePool> = [
  ["agy", "agy", "claude-opus-4-6-thinking", "keyless", 0, "avoid"],
  ["api-airforce", "api-airforce", "x-ai/grok-3", "recurring-daily", 24_000_000, "caution"],
  ["arcee-free", "arcee-ai", "arcee-ai/trinity-large-preview:free", "recurring-daily", 4_800_000, "caution"],
  ["bazaarlink", "bazaarlink", "auto:free", "recurring-daily", 3_600_000, "caution"],
  ["blackbox", "blackbox", "gpt-4o", "keyless", 0, "avoid"],
  ["bluesminds", "bluesminds", "gpt-4o", "recurring-daily", 7_200_000, "ambiguous"],
  ["cerebras", "cerebras", "zai-glm-4.7", "recurring-daily", 30_000_000, "caution"],
  ["cloudflare-ai", "cloudflare-ai", "@cf/meta/llama-3.3-70b-instruct", "recurring-daily", 30_000_000, "caution"],
  ["cohere", "cohere", "command-a-reasoning-08-2025", "recurring-monthly", 800_000, "caution"],
  ["coze", "coze", "claude-3-7-sonnet-20250514", "recurring-daily", 0, "avoid"],
  ["duckduckgo-web", "duckduckgo-web", "gpt-5.4-mini", "keyless", 0, "avoid"],
  ["felo-web", "felo-web", "felo-chat", "keyless", 0, "avoid"],
  ["friendliai", "friendliai", "meta-llama-3.1-70b-instruct", "keyless", 0, "avoid"],
  ["gemini-free", "gemini", "gemini-2.5-flash", "recurring-daily", 60_000_000, "caution"],
  ["github-models", "github-models", "cohere/cohere-command-a", "recurring-daily", 18_000_000, "caution"],
  ["groq", "groq", "meta-llama/llama-4-scout-17b-16e-instruct", "recurring-daily", 15_000_000, "caution"],
  ["hackclub", "hackclub", "meta-llama/llama-3.3-70b-instruct", "keyless", 0, "caution"],
  ["huggingchat", "huggingchat", "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT", "recurring-monthly", 500_000, "caution"],
  ["huggingface", "huggingface", "meta-llama/llama-3.1-8b-instruct", "recurring-monthly", 200_000, "caution"],
  ["iflytek", "iflytek", "generalv3.5", "keyless", 0, "avoid"],
  ["inference-net", "inference-net", "meta-llama/Llama-3.3-70B-Instruct", "recurring-monthly", 0, "caution"],
  ["kiro", "kiro", "claude-sonnet-4.5", "recurring-monthly", 25_000, "avoid"],
  ["liquid", "liquid", "liquid-lfm-40b", "keyless", 0, "unknown"],
  ["llm7-free", "llm7", "gpt-4o-mini-2024-07-18", "recurring-daily", 150_000_000, "caution"],
  ["mistral", "mistral", "mistral-large-latest", "recurring-monthly", 1_000_000_000, "caution"],
  ["morph", "morph", "morph-v3-large", "recurring-monthly", 400_000, "ok"],
  ["muse-spark-web", "muse-spark-web", "muse-spark", "keyless", 0, "avoid"],
  ["nlpcloud", "nlpcloud", "llama-3-8b-instruct", "recurring-monthly", 0, "avoid"],
  ["ollama-cloud", "ollama-cloud", "deepseek-v4-pro", "recurring-monthly", 20_000_000, "ambiguous"],
  ["opencode", "opencode", "big-pickle", "keyless", 0, "avoid"],
  ["openrouter-free", "openrouter", "auto", "recurring-daily", 1_200_000, "caution"],
  ["pollinations", "pollinations", "openai", "keyless", 0, "caution"],
  ["puter", "puter", "gpt-5.5", "keyless", 0, "caution"],
  ["qwen-web", "qwen-web", "qwen3.8-max-preview", "keyless", 0, "avoid"],
  ["reka", "reka", "reka-flash-3", "recurring-monthly", 0, "caution"],
  ["sambanova", "sambanova", "MiniMax-M2.7", "recurring-daily", 6_000_000, "caution"],
  ["sparkdesk", "sparkdesk", "lite", "keyless", 0, "caution"],
  ["t3-web", "t3-web", "claude-opus-4", "recurring-daily", 0, "avoid"],
  ["uncloseai", "uncloseai", "adamo1139/Hermes-3-Llama-3.1-8B-FP8-Dynamic", "keyless", 0, "caution"],
  ["ovhcloud-anon", "ovhcloud", "gpt-oss-120b", "keyless", 0, "ok"],
  ["navy-free", "navy", "shared-pool", "recurring-daily", 4_500_000, "ok"],
  ["aihorde-anon", "aihorde", "aphrodite/TheDrummer/Cydonia-24B-v4.3", "keyless", 0, "ok"],
  ["nara-free", "nara", "tencent-hy3", "recurring-daily", 150_000_000, "caution"],
].map(([poolId, providerId, modelId, freeType, estimatedMonthlyTokens, termsStatus]) =>
  decodeDocumentedFreePool({ poolId, providerId, modelId, freeType, estimatedMonthlyTokens, termsStatus }),
);

export const documentedRecurringTokenEstimate = freePoolSnapshot.reduce(
  (estimatedTokens, freePool) => estimatedTokens + freePool.estimatedMonthlyTokens,
  0,
);

// Every active provider speaks OpenAI Chat except Gemini; one without a credentialId is keyless.
const activeProviderCatalog: ReadonlyArray<ProviderManifest> = [
  {
    providerId: "api-airforce",
    displayName: "API Airforce",
    endpoint: "https://api.airforce/v1/chat/completions",
    credentialId: "api-airforce",
    termsStatus: "caution",
    freeTierWindow: { poolId: "api-airforce", reset: "daily", estimatedTokens: 800_000 },
    models: [{ modelId: "x-ai/grok-3", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://api.airforce/docs",
  },
  {
    providerId: "bazaarlink",
    displayName: "BazaarLink",
    endpoint: "https://bazaarlink.ai/api/v1/chat/completions",
    credentialId: "bazaarlink",
    termsStatus: "caution",
    freeTierWindow: { poolId: "bazaarlink", reset: "daily", estimatedTokens: 120_000 },
    models: [{ modelId: "auto:free", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://bazaarlink.ai/docs",
  },
  {
    providerId: "blackbox",
    displayName: "Blackbox API",
    endpoint: "https://api.blackbox.ai/v1/chat/completions",
    credentialId: "blackbox",
    termsStatus: "avoid",
    freeTierWindow: { poolId: "blackbox", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "gpt-4o", capabilities: ["text", "tools"] }],
    source: "https://docs.blackbox.ai/api-reference/introduction",
  },
  {
    providerId: "bluesminds",
    displayName: "Bluesminds",
    endpoint: "https://api.bluesminds.com/v1/chat/completions",
    credentialId: "bluesminds",
    termsStatus: "ambiguous",
    freeTierWindow: { poolId: "bluesminds", reset: "daily", estimatedTokens: 240_000 },
    models: [{ modelId: "gpt-4o", capabilities: ["text", "tools"] }],
    source: "https://bluesminds.com",
  },
  {
    providerId: "cerebras",
    displayName: "Cerebras",
    endpoint: "https://api.cerebras.ai/v1/chat/completions",
    credentialId: "cerebras",
    termsStatus: "caution",
    freeTierWindow: { poolId: "cerebras", reset: "daily", estimatedTokens: 1_000_000 },
    models: [{ modelId: "zai-glm-4.7", capabilities: ["text", "tools"] }],
    source: "https://inference-docs.cerebras.ai/support/rate-limits",
  },
  {
    providerId: "cloudflare-ai",
    displayName: "Cloudflare Workers AI",
    endpoint: "https://api.cloudflare.com/client/v4/accounts/account-id/ai/v1/chat/completions",
    credentialId: "cloudflare-ai",
    termsStatus: "caution",
    freeTierWindow: { poolId: "cloudflare-ai", reset: "daily", estimatedTokens: 1_000_000 },
    models: [{ modelId: "@cf/meta/llama-3.3-70b-instruct", capabilities: ["text", "tools"] }],
    source: "https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/",
  },
  {
    providerId: "cohere",
    displayName: "Cohere",
    endpoint: "https://api.cohere.com/compatibility/v1/chat/completions",
    credentialId: "cohere",
    termsStatus: "caution",
    freeTierWindow: { poolId: "cohere", reset: "monthly", estimatedTokens: 800_000 },
    models: [{ modelId: "command-a-reasoning-08-2025", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://docs.cohere.com/docs/compatibility-api",
  },
  {
    providerId: "friendliai",
    displayName: "FriendliAI",
    endpoint: "https://api.friendli.ai/serverless/v1/chat/completions",
    credentialId: "friendliai",
    termsStatus: "avoid",
    freeTierWindow: { poolId: "friendliai", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "meta-llama-3.1-70b-instruct", capabilities: ["text", "tools"] }],
    source: "https://friendli.ai/docs/guides/serverless_endpoints/openai_compatibility",
  },
  {
    providerId: "gemini",
    displayName: "Google Gemini",
    endpoint: "https://generativelanguage.googleapis.com/v1beta",
    credentialId: "google-ai-studio",
    termsStatus: "caution",
    freeTierWindow: { poolId: "gemini-free", reset: "daily", estimatedTokens: 2_000_000 },
    models: [{ modelId: "gemini-2.5-flash", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://ai.google.dev/gemini-api/docs/rate-limits",
  },
  {
    providerId: "groq",
    displayName: "Groq",
    endpoint: "https://api.groq.com/openai/v1/chat/completions",
    credentialId: "groq",
    termsStatus: "caution",
    freeTierWindow: { poolId: "groq", reset: "daily", estimatedTokens: 500_000 },
    models: [{ modelId: "meta-llama/llama-4-scout-17b-16e-instruct", capabilities: ["text", "tools"] }],
    source: "https://console.groq.com/docs/rate-limits",
  },
  {
    providerId: "hackclub",
    displayName: "Hack Club AI",
    endpoint: "https://ai.hackclub.com/proxy/v1/chat/completions",
    credentialId: "hackclub",
    termsStatus: "caution",
    freeTierWindow: { poolId: "hackclub", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "meta-llama/llama-3.3-70b-instruct", capabilities: ["text"] }],
    source: "https://ai.hackclub.com",
  },
  {
    providerId: "huggingface",
    displayName: "Hugging Face Inference",
    endpoint: "https://router.huggingface.co/v1/chat/completions",
    credentialId: "huggingface",
    termsStatus: "caution",
    freeTierWindow: { poolId: "huggingface", reset: "monthly", estimatedTokens: 200_000 },
    models: [{ modelId: "meta-llama/llama-3.1-8b-instruct", capabilities: ["text", "tools"] }],
    source: "https://huggingface.co/docs/inference-providers/guides/openai",
  },
  {
    providerId: "iflytek",
    displayName: "iFlytek Spark",
    endpoint: "https://spark-api-open.xf-yun.com/v1/chat/completions",
    credentialId: "iflytek",
    termsStatus: "avoid",
    freeTierWindow: { poolId: "iflytek", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "generalv3.5", capabilities: ["text"] }],
    source: "https://www.xfyun.cn/doc/spark/Web.html",
  },
  {
    providerId: "inference-net",
    displayName: "Inference.net",
    endpoint: "https://api.inference.net/v1/chat/completions",
    credentialId: "inference-net",
    termsStatus: "caution",
    freeTierWindow: { poolId: "inference-net", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "meta-llama/Llama-3.3-70B-Instruct", capabilities: ["text", "tools"] }],
    source: "https://docs.inference.net/features/openai-sdk",
  },
  {
    providerId: "liquid",
    displayName: "Liquid AI",
    endpoint: "https://inference.liquid.ai/v1/chat/completions",
    credentialId: "liquid",
    termsStatus: "unknown",
    freeTierWindow: { poolId: "liquid", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "liquid-lfm-40b", capabilities: ["text"] }],
    source: "https://docs.liquid.ai/api-reference/inference-api",
  },
  {
    providerId: "llm7",
    displayName: "LLM7",
    endpoint: "https://api.llm7.io/v1/chat/completions",
    credentialId: "llm7",
    termsStatus: "caution",
    freeTierWindow: { poolId: "llm7-free", reset: "daily", estimatedTokens: 5_000_000 },
    models: [{ modelId: "gpt-4o-mini-2024-07-18", capabilities: ["text", "tools"] }],
    source: "https://llm7.io",
  },
  {
    providerId: "mistral",
    displayName: "Mistral AI",
    endpoint: "https://api.mistral.ai/v1/chat/completions",
    credentialId: "mistral",
    termsStatus: "caution",
    freeTierWindow: { poolId: "mistral", reset: "monthly", estimatedTokens: 1_000_000_000 },
    models: [{ modelId: "mistral-large-latest", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://docs.mistral.ai/deployment/laplateforme/tier/",
  },
  {
    providerId: "morph",
    displayName: "Morph",
    endpoint: "https://api.morphllm.com/v1/chat/completions",
    credentialId: "morph",
    termsStatus: "ok",
    freeTierWindow: { poolId: "morph", reset: "monthly", estimatedTokens: 400_000 },
    models: [{ modelId: "morph-v3-large", capabilities: ["text", "tools"] }],
    source: "https://docs.morphllm.com/api-reference/introduction",
  },
  {
    providerId: "ollama-cloud",
    displayName: "Ollama Cloud",
    endpoint: "https://ollama.com/v1/chat/completions",
    credentialId: "ollama-cloud",
    termsStatus: "ambiguous",
    freeTierWindow: { poolId: "ollama-cloud", reset: "monthly", estimatedTokens: 20_000_000 },
    models: [{ modelId: "deepseek-v4-pro", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://docs.ollama.com/api/openai-compatibility",
  },
  {
    providerId: "openrouter",
    displayName: "OpenRouter free models",
    endpoint: "https://openrouter.ai/api/v1/chat/completions",
    credentialId: "openrouter-oauth",
    termsStatus: "caution",
    freeTierWindow: { poolId: "openrouter-free", reset: "daily", estimatedTokens: 40_000 },
    models: [{ modelId: "openrouter/free", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://openrouter.ai/docs/guides/overview/auth/oauth",
  },
  {
    providerId: "pollinations",
    displayName: "Pollinations",
    endpoint: "https://gen.pollinations.ai/v1/chat/completions",
    credentialId: "pollinations",
    termsStatus: "caution",
    freeTierWindow: { poolId: "pollinations", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "openai", capabilities: ["text"] }],
    source: "https://github.com/pollinations/pollinations/blob/master/APIDOCS.md",
  },
  {
    providerId: "puter",
    displayName: "Puter",
    endpoint: "https://api.puter.com/puterai/openai/v1/chat/completions",
    credentialId: "puter",
    termsStatus: "caution",
    freeTierWindow: { poolId: "puter", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "gpt-5.5", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://docs.puter.com/AI/chat/",
  },
  {
    providerId: "reka",
    displayName: "Reka",
    endpoint: "https://api.reka.ai/v1/chat/completions",
    credentialId: "reka",
    termsStatus: "caution",
    freeTierWindow: { poolId: "reka", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "reka-flash-3", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://docs.reka.ai/api-reference/chat",
  },
  {
    providerId: "sambanova",
    displayName: "SambaNova",
    endpoint: "https://api.sambanova.ai/v1/chat/completions",
    credentialId: "sambanova",
    termsStatus: "caution",
    freeTierWindow: { poolId: "sambanova", reset: "daily", estimatedTokens: 200_000 },
    models: [{ modelId: "MiniMax-M2.7", capabilities: ["text", "reasoning", "tools"] }],
    source: "https://docs.sambanova.ai/cloud/docs/get-started/overview",
  },
  {
    providerId: "sparkdesk",
    displayName: "SparkDesk",
    endpoint: "https://spark-api-open.xf-yun.com/v1/chat/completions",
    credentialId: "sparkdesk",
    termsStatus: "caution",
    freeTierWindow: { poolId: "sparkdesk", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "lite", capabilities: ["text"] }],
    source: "https://www.xfyun.cn/doc/spark/Web.html",
  },
  {
    providerId: "uncloseai",
    displayName: "UncloseAI",
    endpoint: "https://hermes.ai.unturf.com/v1/chat/completions",
    termsStatus: "caution",
    freeTierWindow: { poolId: "uncloseai", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "adamo1139/Hermes-3-Llama-3.1-8B-FP8-Dynamic", capabilities: ["text"] }],
    source: "https://hermes.ai.unturf.com",
  },
  {
    providerId: "ovhcloud",
    displayName: "OVHcloud AI Endpoints",
    endpoint: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1/chat/completions",
    termsStatus: "ok",
    freeTierWindow: { poolId: "ovhcloud-anon", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "gpt-oss-120b", capabilities: ["text", "reasoning", "tools"] }],
    source:
      "https://help.ovhcloud.com/csm/en-public-cloud-ai-endpoints-getting-started?id=kb_article_view&sysparm_article=KB0065400",
  },
  {
    providerId: "navy",
    displayName: "NavyAI",
    endpoint: "https://api.navy/v1/chat/completions",
    credentialId: "navy",
    termsStatus: "ok",
    freeTierWindow: { poolId: "navy-free", reset: "daily", estimatedTokens: 150_000 },
    models: [{ modelId: "llama-3.3-70b-instruct", capabilities: ["text", "tools"] }],
    source: "https://api.navy",
  },
  {
    providerId: "aihorde",
    displayName: "AI Horde",
    endpoint: "https://oai.aihorde.net/v1/chat/completions",
    termsStatus: "ok",
    freeTierWindow: { poolId: "aihorde-anon", reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId: "aphrodite/TheDrummer/Cydonia-24B-v4.3", capabilities: ["text"] }],
    source: "https://aihorde.net/api",
  },
  {
    providerId: "nara",
    displayName: "NaraRouter",
    endpoint: "https://router.bynara.id/v1/chat/completions",
    credentialId: "nara",
    termsStatus: "caution",
    freeTierWindow: { poolId: "nara-free", reset: "daily", estimatedTokens: 5_000_000 },
    models: [{ modelId: "tencent-hy3", capabilities: ["text"] }],
    source: "https://bynara.id",
  },
].map((provider) =>
  decodeProviderManifest({
    ...provider,
    protocolFamily: provider.providerId === "gemini" ? "google-generative" : "openai-chat",
    authentication: provider.credentialId === undefined ? "keyless" : "api-key",
    acknowledgementVersion,
    activation: "active",
  }),
);

const unavailableProviderCatalog: ReadonlyArray<ProviderManifest> = [
  {
    providerId: "coze",
    displayName: "Coze",
    endpoint: "https://api.coze.com/v3/chat",
    termsStatus: "avoid",
    poolId: "coze",
    modelId: "claude-3-7-sonnet-20250514",
    unavailableReason: "unsupported-protocol",
    source: "https://www.coze.com/open/docs/developer_guides/coze_api_overview",
  },
  {
    providerId: "nlpcloud",
    displayName: "NLP Cloud",
    endpoint: "https://api.nlpcloud.io/v1/gpu/llama-3-8b-instruct/chatbot",
    termsStatus: "avoid",
    poolId: "nlpcloud",
    modelId: "llama-3-8b-instruct",
    unavailableReason: "unsupported-protocol",
    source: "https://docs.nlpcloud.com/#chatbot-and-conversational-ai",
  },
  {
    providerId: "github-models",
    displayName: "GitHub Models",
    endpoint: "https://models.github.ai/inference/chat/completions",
    termsStatus: "caution",
    poolId: "github-models",
    modelId: "cohere/cohere-command-a",
    unavailableReason: "retired-contract",
    source: "https://docs.github.com/en/github-models/prototyping-with-ai-models",
  },
  {
    providerId: "agy",
    displayName: "AGY",
    endpoint: "https://cloudcode-pa.googleapis.com",
    termsStatus: "avoid",
    poolId: "agy",
    modelId: "claude-opus-4-6-thinking",
    unavailableReason: "synthetic-identity",
    source: "https://github.com/diegosouzapw/OmniRoute",
  },
  {
    providerId: "arcee-ai",
    displayName: "Arcee free relay",
    endpoint: "https://api.kilo.ai/api/gateway/chat/completions",
    termsStatus: "caution",
    poolId: "arcee-free",
    modelId: "arcee-ai/trinity-large-preview:free",
    unavailableReason: "unverified-contract",
    source: "https://github.com/diegosouzapw/OmniRoute",
  },
  {
    providerId: "duckduckgo-web",
    displayName: "DuckDuckGo web chat",
    endpoint: "https://duckduckgo.com/duckchat/v1/chat",
    termsStatus: "avoid",
    poolId: "duckduckgo-web",
    modelId: "gpt-5.4-mini",
    unavailableReason: "browser-cookie",
    source: "https://duckduckgo.com/duckai",
  },
  {
    providerId: "felo-web",
    displayName: "Felo web search",
    endpoint: "https://felo.ai/api-proxy/main/search/threads",
    termsStatus: "avoid",
    poolId: "felo-web",
    modelId: "felo-chat",
    unavailableReason: "browser-cookie",
    source: "https://felo.ai",
  },
  {
    providerId: "huggingchat",
    displayName: "HuggingChat",
    endpoint: "https://huggingface.co/chat/conversation",
    termsStatus: "caution",
    poolId: "huggingchat",
    modelId: "baidu/ERNIE-4.5-VL-424B-A47B-Base-PT",
    unavailableReason: "browser-cookie",
    source: "https://huggingface.co/chat",
  },
  {
    providerId: "kiro",
    displayName: "Kiro",
    endpoint: "https://codewhisperer.us-east-1.amazonaws.com/generateAssistantResponse",
    termsStatus: "avoid",
    poolId: "kiro",
    modelId: "claude-sonnet-4.5",
    unavailableReason: "synthetic-identity",
    source: "https://kiro.dev",
  },
  {
    providerId: "muse-spark-web",
    displayName: "Meta AI web",
    endpoint: "https://www.meta.ai/api/graphql",
    termsStatus: "avoid",
    poolId: "muse-spark-web",
    modelId: "muse-spark",
    unavailableReason: "browser-cookie",
    source: "https://www.meta.ai",
  },
  {
    providerId: "opencode",
    displayName: "OpenCode synthetic identity",
    endpoint: "https://opencode.ai/zen/v1/chat/completions",
    termsStatus: "avoid",
    poolId: "opencode",
    modelId: "big-pickle",
    unavailableReason: "synthetic-identity",
    source: "https://opencode.ai/docs/zen/",
  },
  {
    providerId: "qwen-web",
    displayName: "Qwen web chat",
    endpoint: "https://chat.qwen.ai/api/chat/completions",
    termsStatus: "avoid",
    poolId: "qwen-web",
    modelId: "qwen3.8-max-preview",
    unavailableReason: "browser-cookie",
    source: "https://chat.qwen.ai",
  },
  {
    providerId: "t3-web",
    displayName: "T3 Chat web",
    endpoint: "https://t3.chat/api/chat",
    termsStatus: "avoid",
    poolId: "t3-web",
    modelId: "claude-opus-4",
    unavailableReason: "browser-cookie",
    source: "https://t3.chat",
  },
].map(({ poolId, modelId, ...provider }) =>
  decodeProviderManifest({
    ...provider,
    protocolFamily: "openai-chat",
    authentication: "keyless",
    acknowledgementVersion,
    activation: "unavailable",
    freeTierWindow: { poolId, reset: "unquantified", estimatedTokens: 0 },
    models: [{ modelId, capabilities: ["text"] }],
  }),
);

export const freeProviderCatalog: ReadonlyArray<ProviderManifest> = [
  ...activeProviderCatalog,
  ...unavailableProviderCatalog,
];
